// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("network.http.http3.enabled", true);

user_pref("app.update.auto", false);
user_pref("app.update.enabled", false);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.offline.enable", false);
user_pref("browser.casting.enabled", false);
user_pref("browser.startup.homepage", "about:blank");
user_pref("devtools.cache.disabled", true);
user_pref("devtools.toolbox.selectedTool", "netmonitor");
//user_pref("dom.storage.enabled", false);
user_pref("extensions.blocklist.enabled", false);
user_pref("extensions.getAddons.cache.enabled", false);
user_pref("extensions.update.autoUpdateDefault", false);
user_pref("extensions.update.enabled", false);
user_pref("network.dnsCacheEntries", 0);
user_pref("security.OCSP.enable", 1);
